### ISSUE TITLE
CompositeKnot.state will be called even if the same state will be emitted

### ISSUE THREAD

**Issue by StefMa** [beworker/knot#23]
Given this test:
```kotlin
    @Test
    fun compositeKnotTest() {
        data class X(val x: Int = 0)

        val compositeKnot = compositeKnot<X> {
            this.state {
                initial = X()
            }
        }
        compositeKnot.registerPrime<Unit, Action> {
            changes {
                reduce<Unit> {
                    return@reduce X().only
                }
            }
            events {
                source {
                    compositeKnot.state
                        .doOnNext { println(it) }
                        .map { Unit }
                }
            }
        }
        compositeKnot.compose()
        compositeKnot.change.accept(Unit)
        Thread.sleep(3000)
    }
```
I would expect that after I call `compositeKnot.change.accept(Unit)`, the reducer get called, which creates a new `X()` and that's it.
Why don't I expect a call to `doOnNext`? 
Because `X` is a `data class` and 100% equal to the previous state.
But what happen currently?
We run into an endless loop.
After the `reducer` creates a new `X()` the `compositeKnot.state` get called, return a new `Change` which will call the `reducer` which creates a new `X()` which calls the `compositeKnot.state`.... recursively...

As I said, I would expect (because the new X is equal to the new X) the `compositeKnot.state` would not be triggered.

**Comment by beworker** [comment]
The library applies `===` operator to the state for checking whether the state returned from reducer was changed. Thus the state considered to be the same for the same instance only. This is done on purpose because some states can be really heavy (they can hold big objects) and we didn't want to have that "heavy" comparison computation in the library. This is responsibility of the client.

Because reducer in your example creates a new instance, the state is considered to be changed and it gets dispatched down the stream. There is an endless loop in the example. To resolve it you should either return `this.only` from the reducer or apply `distinctUntilChanged()` to the `compositeKnot.state` in `events` section. Knot cannot resolve such endless loops automatically.

**Comment by StefMa** [comment]
Thank you for your detail explanation and hints to fix my issue 👌.

Because this is a actively design decision I'll close this issue 👍
